=== CyberTailor/ru.index.community/src/data/schemas/groups.json
{
    "$schema": "http://json-schema.org/schema",
    "$id": "http://fedi.inex.dev/schemas/instances.json",
    "type": "object",
    "properties": {
        "handle": {
            "type": "string"
        },
        "uri": {
            "type": "string"
        },
        "title": {
            "type": "string"
        },
        "short_description": {
            "type": "string"
        },
        "thumbnail": {
            "type": "string"
        },
        "icon": {
            "type": "string"
        },
        "members": {
            "type": "integer"
        }
    },
    "required": [
        "uri",
        "handle",
        "title"
    ]
}

=== CyberTailor/ru.index.community/src/data/groups/utopia@mastodon.ml.json
{
    "$schema": "../schemas/groups.json",
    "uri": "mastodon.ml/@utopia",
    "handle": "@utopia@mastodon.ml",
    "title": "Utopia",
    "short_description": "Группа \"Утопия\" предназначена для обсуждения путей создания и принципов существования свободного, независимого общества, альтернативного существующим жестким государственным и корпоративным структурам",
    "icon": "utopia@mastodon.ml.icon.png",
    "thumbnail": "utopia@mastodon.ml.banner.png",
    "members": 46
}

=== CyberTailor/ru.index.community/src/data/groups/ru@lor.sh.json
{
    "$schema": "../schemas/groups.json",
    "uri": "lor.sh/@ru",
    "handle": "@ru@lor.sh",
    "title": "ru",
    "short_description": "Агрегатор публичных сообщений с lor.sh, mstdn.netwhood.online, mastodon.ml и aspirant.de.",
    "icon": "ru@lor.sh.icon.png",
    "thumbnail": "ru@lor.sh.banner.png",
    "members": 230
}

=== CyberTailor/ru.index.community/src/data/groups/WAAbDvy4@soc.phreedom.club.json
{
    "$schema": "../schemas/groups.json",
    "uri": "soc.phreedom.club/users/WAAbDvy4",
    "handle": "@WAAbDvy4@soc.phreedom.club",
    "title": "ШизоБот",
    "short_description": "Бот-группа для криптошизиков, криптоанархистов, специалистов ИБ и т.д.",
    "icon": "WAAbDvy4@soc.phreedom.club.icon.png",
    "members": 18
}

=== CyberTailor/ru.index.community/src/data/groups/rf@mastodon.ml.json
{
    "$schema": "../schemas/groups.json",
    "uri": "mastodon.ml/@rf",
    "handle": "@rf@mastodon.ml",
    "title": "R–æ—Å—Å–∏–π—Å–∫–∞—èüêªF–µ–¥–µ—Ä–∞—Ü–∏—è",
    "short_description": "–û–±—ä–µ–¥–∏–Ω–µ–Ω–∏–µ —Ä—É—Å—Å–∫–æ—è–∑—ã—á–Ω—ã—Ö –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª–µ–π –§–µ–¥–∏–≤–µ—Ä—Å–∞, —Å–∞–º–∞—è –ø–æ–ø—É–ª—è—Ä–Ω–∞—è –≥—Ä—É–ø–ø–∞ –æ–±—â–µ–π —Ç–µ–º–∞—Ç–∏–∫–∏",
    "members": 1238,
    "icon": "rf@mastodon.ml.icon.png",
    "thumbnail": "rf@mastodon.ml.banner.png"
}

=== CyberTailor/ru.index.community/src/data/groups/city4people@zhub.link.json
{
    "$schema": "../schemas/groups.json",
    "uri": "zhub.link/@city4people",
    "handle": "@city4people@zhub.link",
    "title": "городДляЛюдей",
    "short_description": "Узкотематическая группа про урбанистику, архитектуру и фантастику",
    "icon": "city4people@zhub.link.icon.png",
    "thumbnail": "city4people@zhub.link.banner.png"
}

=== CyberTailor/ru.index.community/src/data/groups/vote@techporn.club.json
{
    "$schema": "../schemas/groups.json",
    "uri": "techporn.club/@vote",
    "handle": "@vote@techporn.club",
    "title": "Опросник",
    "short_description": "Любишь проходить опросы? Хочешь поучаствовать в сборе статистики о русскоговорящих пользователях в федиверсе? Тогда подпишись чтобы видите проходящие опросы в своей ленте.",
    "icon": "vote@techporn.club.icon.png",
    "thumbnail": "vote@techporn.club.banner.png",
    "members": 18
}
