=== CyberTailor/ru.index.community/src/data/schemas/instances.json
{
    "$schema": "http://json-schema.org/schema",
    "$id": "http://fedi.inex.dev/schemas/instances.json",
    "type": "object",
    "properties": {
        "uri": {
            "type": "string"
        },
        "title": {
            "type": "string"
        },
        "short_description": {
            "type": "string"
        },
        "thumbnail": {
            "type": "string"
        },
        "users": {
            "type": "object",
            "properties": {
                "total": {
                    "type": "integer"
                },
                "active_month": {
                    "type": "integer"
                },
                "active_halfyear": {
                    "type": "integer"
                }
            }
        },
        "software": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                },
                "repository": {
                    "type": "string"
                }
            },
            "required": [
                "name"
            ]
        },
        "registration": {
            "type": "object",
            "properties": {
                "available": {
                    "type": "boolean"
                },
                "approval_required": {
                    "type": "boolean"
                },
                "invite_required": {
                    "type": "boolean"
                },
                "email_required": {
                    "type": "boolean"
                }
            }
        },
        "administration": {
            "type": "object",
            "properties": {
                "contact_email": {
                    "type": "string"
                },
                "server_location": {
                    "type": "integer"
                },
                "bus_factor": {
                    "type": "integer"
                },
                "backups_policy": {
                    "type": "string"
                },
                "federation_policies": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "cloudflare": {
                    "type": "boolean"
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "posting": {
            "type": "object",
            "properties": {
                "max_chars": {
                    "type": "integer"
                },
                "post_formats": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "poll_settings": {
                    "type": "object",
                    "properties": {
                        "max_expiration": {
                            "type": "integer"
                        },
                        "max_option_chars": {
                            "type": "integer"
                        },
                        "max_options": {
                            "type": "integer"
                        },
                        "min_expiration": {
                            "type": "integer"
                        }
                    }
                },
                "upload_limits": {
                    "type": "object",
                    "properties": {
                        "avatar": {
                            "type": "integer"
                        },
                        "background": {
                            "type": "integer"
                        },
                        "banner": {
                            "type": "integer"
                        },
                        "general": {
                            "type": "integer"
                        }
                    }
                },
                "storage_quota": {
                    "type": "integer"
                }
            }
        },
        "music_library": {
            "type": "object",
            "properties": {
                "federation_enabled": {
                    "type": "boolean"
                },
                "anonymous_can_listen": {
                    "type": "boolean"
                },
                "tracks": {
                    "type": "object",
                    "properties": {
                        "total": {
                            "type": "integer"
                        }
                    }
                },
                "artists": {
                    "type": "object",
                    "properties": {
                        "total": {
                            "type": "integer"
                        }
                    }
                },
                "albums": {
                    "type": "object",
                    "properties": {
                        "total": {
                            "type": "integer"
                        }
                    }
                },
                "music": {
                    "type": "object",
                    "properties": {
                        "hours": {
                            "type": "number"
                        }
                    }
                }
            }
        }
    },
    "required": [
        "uri",
        "software"
    ]
}

=== CyberTailor/ru.index.community/src/data/instances/social.inex.rocks.json
{
    "$schema": "../schemas/instances.json",
    "uri": "social.inex.rocks",
    "short_description": "Just a little IT-Brony Mastodon node for friends.",
    "thumbnail": "social.inex.rocks.png",
    "software": {
        "name": "mastodon",
        "version": "3.2.0"
    },
    "users": {
        "total": 42,
        "active_halfyear": 46,
        "active_month": 26
    },
    "administration": {
        "backups_policy": "daily",
        "bus_factor": 2,
        "contact_email": "mastodon@inex.rocks",
        "federation_policies": [
            "https://raw.githubusercontent.com/pixeldesu/fediverse-friendly-moderation-covenant/master/covenant.md"
        ],
        "server_location": 276,
        "provider": "Hetzner"
    },
    "registration": {
        "approval_required": true,
        "available": true,
        "email_required": true,
        "invite_required": true
    },
    "posting": {
        "max_chars": 500,
        "poll_settings": {
            "max_option_chars": 25,
            "max_options": 4
        },
        "post_formats": [
            "text/plain"
        ]
    }
}

=== CyberTailor/ru.index.community/src/data/instances/sect.sunbutt.faith.json
{
    "$schema": "../schemas/instances.json",
    "uri": "sect.sunbutt.faith",
    "title": "Celestianism Sect",
    "short_description": "Уютное русскоязычное место в глобальной сети Fediverse для свободного и дружелюбного общения имени Её Величия и Размера — принцессы Селестии.",
    "thumbnail": "sect.sunbutt.faith.png",
    "software": {
        "name": "pleroma",
        "version": "2.2.0-0-gfb0e340-release-2-2-0",
        "repository": "https://git.pleroma.social/pleroma/pleroma"
    },
    "users": {
        "total": 36
    },
    "administration": {
        "backups_policy": "daily",
        "bus_factor": 4,
        "contact_email": "commagray@sunbutt.faith",
        "server_location": 804
    },
    "registration": {
        "approval_required": false,
        "available": true,
        "email_required": true,
        "invite_required": false
    },
    "posting": {
        "max_chars": 5000,
        "poll_settings": {
            "max_option_chars": 200,
            "max_options": 20,
            "max_expiration": 31536000,
            "min_expiration": 0
        },
        "post_formats": [
            "text/plain",
            "text/html",
            "text/markdown",
            "text/bbcode"
        ],
        "upload_limits": {
            "avatar": 2000000,
            "background": 4000000,
            "banner": 4000000,
            "general": 16000000
        }
    }
}

=== CyberTailor/ru.index.community/src/data/instances/ru.social.json
{
    "$schema": "../schemas/instances.json",
    "uri": "ru.social",
    "short_description": "Региональный Российский узел сети Fediverse.",
    "thumbnail": "ru.social.png",
    "software": {
        "name": "mastodon",
        "version": "3.3.0"
    },
    "users": {
        "total": 193
    },
    "posting": {
        "max_chars": 500,
        "poll_settings": {
            "max_option_chars": 25,
            "max_options": 4
        },
        "post_formats": [
            "text/plain"
        ]
    },
    "administration": {
        "provider": "Selectel"
    }
}

=== CyberTailor/ru.index.community/src/data/instances/mk.phreedom.club.json
{
    "$schema": "../schemas/instances.json",
    "uri": "mk.phreedom.club",
    "short_description": "Клуб \"Свобода\" предоставляет всем желающим альтернативу централизованным корпоративным сервисам. ",
    "thumbnail": "soc.phreedom.club.png",
    "software": {
        "name": "misskey",
        "version": "12.119.0"
    },
    "users": {
        "total": 23
    },
    "posting": {
        "max_chars": 3000,
        "poll_settings": {
            "max_option_chars": 25,
            "max_options": 4
        },
        "post_formats": [
            "text/plain"
        ]
    },
    "administration": {
        "backups_policy": "daily",
        "provider": "FlokiNet"
    },
    "registration": {
        "available": true
    }
}

=== CyberTailor/ru.index.community/src/data/instances/indiefedi.party.json
{
    "$schema": "../schemas/instances.json",
    "uri": "indiefedi.party",
    "short_description": "Привет! Это indiefedi.party — инстанс Pleroma, созданный с целью разбавить однообразие визуального контента федивёрса. Категорически приветствуются музыканты и причастные. Художников и мемемэйкеров в интернетах — каждый второй, а независимых музыкантов — кот наплакал. You are very welcome, тем более, движок pleroma располагает, цепляй музыку к постам хоть целыми альбомами. Создадим самый музыкальный инстанс!",
    "thumbnail": "indiefedi.party.png",
    "software": {
        "name": "pleroma"
    },
    "users": {
        "total": 48
    },
    "posting": {
        "max_chars": 50000
    },
    "administration": {
        "provider": "OVH SAS"
    }
}

=== CyberTailor/ru.index.community/src/data/instances/mastodon.ml.json
{
    "$schema": "../schemas/instances.json",
    "uri": "mastodon.ml",
    "short_description": "Русская нода социальной сети \"Мастодонт\", части Fediverse - всемирной федерации социальных сетей. Зона общения, свободная от рекламы и шпионажа, теперь и в России.",
    "thumbnail": "mastodon.ml.png",
    "software": {
        "name": "mastodon",
        "version": "3.2.0"
    },
    "users": {
        "total": 1055
    },
    "posting": {
        "max_chars": 1000,
        "poll_settings": {
            "max_option_chars": 25,
            "max_options": 4
        },
        "post_formats": [
            "text/plain"
        ]
    },
    "administration": {
        "provider": "Hetzner"
    }
}

=== CyberTailor/ru.index.community/src/data/instances/quietplace.xyz.json
{
    "$schema": "../schemas/instances.json",
    "uri": "quietplace.xyz",
    "title": "A Quiet Place",
    "short_description": "This is a city that holds the many dreams and stories of its people.\nMost of these stories are left untold.\nBut some few find solace in the embrace of bricks and wood and glass.\nThey are told over drinks, then take up residence in some stranger's memories.\nIn one corner of the city stand a Quiet Place.\nA place that is only open when the sun is sleeping.\nA place where people share their stories.\nAnd these are their stories...",
    "thumbnail": "quietplace.xyz.png",
    "software": {
        "name": "misskey"
    },
    "users": {
        "total": 88
    },
    "posting": {
        "max_chars": 5000
    },
    "administration": {
        "provider": "Scaleway"
    }
}

=== CyberTailor/ru.index.community/src/data/instances/mstdn.netwhood.online.json
{
    "$schema": "../schemas/instances.json",
    "uri": "mstdn.netwhood.online",
    "short_description": "Network neighborhood / Сетевое соседство это открытое сообщество людей, увлекающихся средствами коммуникаций, сетями связи, информационными системами, программированием, и в целом всем, что так или иначе связано с информацией, её движением и влиянием на нашу жизнь.",
    "thumbnail": "mstdn.netwhood.online.png",
    "software": {
        "name": "mastodon",
        "version": "3.2.0"
    },
    "users": {
        "total": 126
    },
    "posting": {
        "max_chars": 500,
        "poll_settings": {
            "max_option_chars": 25,
            "max_options": 4
        },
        "post_formats": [
            "text/plain"
        ]
    },
    "administration": {
        "provider": "OVH SAS"
    }
}
