=== CyberTailor/ru.index.community/src/data/schemas/instances.json
{
    "$schema": "http://json-schema.org/schema",
    "$id": "http://fedi.inex.dev/schemas/instances.json",
    "type": "object",
    "properties": {
        "uri": {
            "type": "string"
        },
        "title": {
            "type": "string"
        },
        "short_description": {
            "type": "string"
        },
        "thumbnail": {
            "type": "string"
        },
        "users": {
            "type": "object",
            "properties": {
                "total": {
                    "type": "integer"
                },
                "active_month": {
                    "type": "integer"
                },
                "active_halfyear": {
                    "type": "integer"
                }
            }
        },
        "software": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                },
                "repository": {
                    "type": "string"
                }
            },
            "required": [
                "name"
            ]
        },
        "registration": {
            "type": "object",
            "properties": {
                "available": {
                    "type": "boolean"
                },
                "approval_required": {
                    "type": "boolean"
                },
                "invite_required": {
                    "type": "boolean"
                },
                "email_required": {
                    "type": "boolean"
                }
            }
        },
        "administration": {
            "type": "object",
            "properties": {
                "contact_email": {
                    "type": "string"
                },
                "server_location": {
                    "type": "integer"
                },
                "bus_factor": {
                    "type": "integer"
                },
                "backups_policy": {
                    "type": "string"
                },
                "federation_policies": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "cloudflare": {
                    "type": "boolean"
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "posting": {
            "type": "object",
            "properties": {
                "max_chars": {
                    "type": "integer"
                },
                "post_formats": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "poll_settings": {
                    "type": "object",
                    "properties": {
                        "max_expiration": {
                            "type": "integer"
                        },
                        "max_option_chars": {
                            "type": "integer"
                        },
                        "max_options": {
                            "type": "integer"
                        },
                        "min_expiration": {
                            "type": "integer"
                        }
                    }
                },
                "upload_limits": {
                    "type": "object",
                    "properties": {
                        "avatar": {
                            "type": "integer"
                        },
                        "background": {
                            "type": "integer"
                        },
                        "banner": {
                            "type": "integer"
                        },
                        "general": {
                            "type": "integer"
                        }
                    }
                },
                "storage_quota": {
                    "type": "integer"
                }
            }
        },
        "music_library": {
            "type": "object",
            "properties": {
                "federation_enabled": {
                    "type": "boolean"
                },
                "anonymous_can_listen": {
                    "type": "boolean"
                },
                "tracks": {
                    "type": "object",
                    "properties": {
                        "total": {
                            "type": "integer"
                        }
                    }
                },
                "artists": {
                    "type": "object",
                    "properties": {
                        "total": {
                            "type": "integer"
                        }
                    }
                },
                "albums": {
                    "type": "object",
                    "properties": {
                        "total": {
                            "type": "integer"
                        }
                    }
                },
                "music": {
                    "type": "object",
                    "properties": {
                        "hours": {
                            "type": "number"
                        }
                    }
                }
            }
        }
    },
    "required": [
        "uri",
        "software"
    ]
}

=== CyberTailor/ru.index.community/src/data/instances/udongein.xyz.json
{
    "$schema": "../schemas/instances.json",
    "uri": "udongein.xyz",
    "short_description": "Your friendly local Reisen U. Inaba shrine!",
    "thumbnail": "udongein.xyz.png",
    "software": {
        "name": "pleroma"
    },
    "users": {
        "total": 168
    },
    "posting": {
        "max_chars": 10000
    },
    "administration": {
        "provider": "Hetzner"
    }
}

=== CyberTailor/ru.index.community/src/data/instances/point.community.json
{
    "$schema": "../schemas/instances.json",
    "uri": "point.community",
    "short_description": "Поддерживаем манифест свободного общения и приветствуем самоорганизацию: каждый сам за себя решает что писать и что читать (в пределах уголовного кодекса). Инстанс закрыт от незарегистрированых пользователей и поисковых ботов. Основные пользователи - выходцы из Point.IM.",
    "thumbnail": "point.community.png",
    "software": {
        "name": "friendica"
    },
    "users": {
        "total": 34
    },
    "posting": {
        "max_chars": 65000
    },
    "administration": {
        "cloudflare": true
    }
}

=== CyberTailor/ru.index.community/src/data/instances/expired.mentality.rip.json
{
    "$schema": "../schemas/instances.json",
    "uri": "expired.mentality.rip",
    "short_description": "Expired Mentality или EMR — это дружелюбный инстанс со свободной тематикой и лёгкой модерацией. На выбор несколько оболочек: от стандартных до Soapbox и легковесного Bloat.",
    "thumbnail": "expired.mentality.rip.png",
    "software": {
        "name": "pleroma"
    },
    "users": {
        "total": 206
    },
    "posting": {
        "max_chars": 65535
    },
    "administration": {
        "provider": "Hetzner"
    }
}

=== CyberTailor/ru.index.community/src/data/instances/shitpost.poridge.club.json
{
    "$schema": "../schemas/instances.json",
    "uri": "shitpost.poridge.club",
    "title": "[Shitpost] PoridgeClub",
    "short_description": "Инстанс с практически полной свободой слова, адекватным админом, кучей плюшек и стабильной работой.",
    "thumbnail": "shitpost.poridge.club.png",
    "software": {
        "name": "misskey",
        "version": "12.92.0"
    },
    "users": {
        "total": 23
    },
    "posting": {
        "max_chars": 5000,
        "poll_settings": {
            "max_option_chars": 25,
            "max_options": 4
        },
        "post_formats": [
            "text/plain"
        ]
    },
    "administration": {
        "backups_policy": "weekly",
        "provider": "ИХЦ",
        "server_location": 643
    },
    "registration": {
        "available": true
    }
}

=== CyberTailor/ru.index.community/src/data/instances/freehub.space.json
{
    "$schema": "../schemas/instances.json",
    "uri": "freehub.space",
    "short_description": "FreeHub — хаб русскоязычного сегмента сети Hubzilla, который создавался как место общения свободных людей. Мы приветствуем всех, для кого личная свобода - не пустой звук.",
    "thumbnail": "freehub.space.png",
    "software": {
        "name": "hubzilla"
    },
    "users": {
        "total": 39
    }
}

=== CyberTailor/ru.index.community/src/data/instances/soc.phreedom.club.json
{
    "$schema": "../schemas/instances.json",
    "uri": "soc.phreedom.club",
    "short_description": "Клуб \"Свобода\" предоставляет всем желающим альтернативу централизованным корпоративным сервисам. Основные принципы — простота, минимализм и надёжность. ",
    "thumbnail": "soc.phreedom.club.png",
    "software": {
        "name": "pleroma"
    },
    "users": {
        "total": 127
    },
    "posting": {
        "max_chars": 65535,
        "poll_settings": {
            "max_option_chars": 200,
            "max_options": 20,
            "max_expiration": 31536000,
            "min_expiration": 0
        },
        "post_formats": [
            "text/plain",
            "text/html",
            "text/markdown",
            "text/bbcode"
        ],
        "upload_limits": {
            "avatar": 2000000,
            "background": 4000000,
            "banner": 4000000,
            "general": 16000000
        }
    }
}

=== CyberTailor/ru.index.community/src/data/instances/craba.cab.json
{
    "$schema": "../schemas/instances.json",
    "uri": "craba.cab",
    "title": "Mastodon Craba",
    "short_description": "Пространство для русскоязычных левачек, феминисток, квир-людей и их союзников, которые хотят найти альтернативу твиттеру. Становитесь крабами!",
    "users": {
        "total": 19,
        "active_month": 19,
        "active_halfyear": 19
    },
    "software": {
        "name": "mastodon",
        "version": "4.1.4"
    },
    "registration": {
        "invite_required": true
    },
    "administration": {
        "contact_email": "info@craba.cab",
        "bus_factor": 1,
        "cloudflare": true,
        "provider": "Oracle"
    },
    "posting": {
        "max_chars": 500,
        "post_formats": [
            "text/plain"
        ],
        "poll_settings": {
            "max_options": 4
        }
    }
}

=== CyberTailor/ru.index.community/src/data/instances/hubzilla.dark-alexandr.net.json
{
    "$schema": "../schemas/instances.json",
    "uri": "hubzilla.dark-alexandr.net",
    "short_description": "Личный эксперементальный сервер с открытой регистрацией, используются свежие версии софта, часто эксперементальные, никаких гарантий не даю.",
    "software": {
        "name": "hubzilla"
    },
    "users": {
        "total": 14
    },
    "registration": {
        "approval_required": true,
        "available": true,
        "email_required": true
    },
    "administration": {
        "backups_policy": "weekly"
    }
}
