=== CyberTailor/ru.index.community/src/data/schemas/instances.json
{
    "$schema": "http://json-schema.org/schema",
    "$id": "http://fedi.inex.dev/schemas/instances.json",
    "type": "object",
    "properties": {
        "uri": {
            "type": "string"
        },
        "title": {
            "type": "string"
        },
        "short_description": {
            "type": "string"
        },
        "thumbnail": {
            "type": "string"
        },
        "users": {
            "type": "object",
            "properties": {
                "total": {
                    "type": "integer"
                },
                "active_month": {
                    "type": "integer"
                },
                "active_halfyear": {
                    "type": "integer"
                }
            }
        },
        "software": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                },
                "repository": {
                    "type": "string"
                }
            },
            "required": [
                "name"
            ]
        },
        "registration": {
            "type": "object",
            "properties": {
                "available": {
                    "type": "boolean"
                },
                "approval_required": {
                    "type": "boolean"
                },
                "invite_required": {
                    "type": "boolean"
                },
                "email_required": {
                    "type": "boolean"
                }
            }
        },
        "administration": {
            "type": "object",
            "properties": {
                "contact_email": {
                    "type": "string"
                },
                "server_location": {
                    "type": "integer"
                },
                "bus_factor": {
                    "type": "integer"
                },
                "backups_policy": {
                    "type": "string"
                },
                "federation_policies": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "cloudflare": {
                    "type": "boolean"
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "posting": {
            "type": "object",
            "properties": {
                "max_chars": {
                    "type": "integer"
                },
                "post_formats": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "poll_settings": {
                    "type": "object",
                    "properties": {
                        "max_expiration": {
                            "type": "integer"
                        },
                        "max_option_chars": {
                            "type": "integer"
                        },
                        "max_options": {
                            "type": "integer"
                        },
                        "min_expiration": {
                            "type": "integer"
                        }
                    }
                },
                "upload_limits": {
                    "type": "object",
                    "properties": {
                        "avatar": {
                            "type": "integer"
                        },
                        "background": {
                            "type": "integer"
                        },
                        "banner": {
                            "type": "integer"
                        },
                        "general": {
                            "type": "integer"
                        }
                    }
                },
                "storage_quota": {
                    "type": "integer"
                }
            }
        },
        "music_library": {
            "type": "object",
            "properties": {
                "federation_enabled": {
                    "type": "boolean"
                },
                "anonymous_can_listen": {
                    "type": "boolean"
                },
                "tracks": {
                    "type": "object",
                    "properties": {
                        "total": {
                            "type": "integer"
                        }
                    }
                },
                "artists": {
                    "type": "object",
                    "properties": {
                        "total": {
                            "type": "integer"
                        }
                    }
                },
                "albums": {
                    "type": "object",
                    "properties": {
                        "total": {
                            "type": "integer"
                        }
                    }
                },
                "music": {
                    "type": "object",
                    "properties": {
                        "hours": {
                            "type": "number"
                        }
                    }
                }
            }
        }
    },
    "required": [
        "uri",
        "software"
    ]
}

=== CyberTailor/ru.index.community/src/data/instances/lor.sh.json
{
    "$schema": "../schemas/instances.json",
    "uri": "lor.sh",
    "short_description": "lor.sh is yet another mastodon instance.",
    "thumbnail": "lor.sh.png",
    "software": {
        "name": "mastodon",
        "version": "3.2.0"
    },
    "users": {
        "total": 627
    },
    "posting": {
        "max_chars": 16384,
        "poll_settings": {
            "max_option_chars": 25,
            "max_options": 4
        },
        "post_formats": [
            "text/plain"
        ]
    },
    "administration": {
        "cloudflare": true
    }
}

=== CyberTailor/ru.index.community/src/data/instances/pleroma.dark-alexandr.net.json
{
    "$schema": "../schemas/instances.json",
    "uri": "pleroma.dark-alexandr.net",
    "short_description": "Личный эксперементальный сервер с открытой регистрацией, используются свежие версии софта, часто эксперементальные, никаких гарантий не даю.",
    "software": {
        "name": "pleroma"
    },
    "users": {
        "total": 4
    },
    "registration": {
        "approval_required": true,
        "available": true,
        "email_required": true
    },
    "administration": {
        "backups_policy": "weekly"
    },
    "posting": {
        "max_chars": 655360
    }
}

=== CyberTailor/ru.index.community/src/data/instances/zhub.link.json
{
    "$schema": "../schemas/instances.json",
    "uri": "zhub.link",
    "short_description": "Небольшой сервер социальной сети Mastodon для русскоязычной аудитории. Сам сервер расположен дома (в EU) у админа, но на хорошем железе, в KVM-виртуалке, обеспечен бесперебойным питанием и подключен к Интернет гигабитным каналом. Так же, домен резолвится и в IPv6-адрес сети Yggdrasil, соответственно, работает через неё тоже. Цензура не предусмотрена. Присоединяйтесь.",
    "thumbnail": "zhub.link.png",
    "software": {
        "name": "mastodon",
        "version": "3.2.0"
    },
    "users": {
        "total": 28
    },
    "posting": {
        "max_chars": 500,
        "poll_settings": {
            "max_option_chars": 25,
            "max_options": 4
        },
        "post_formats": [
            "text/plain"
        ]
    }
}
